#-----------------IMPORTS-----------------
import os 
import asyncio
import requests as rr

from pyrogram import filters
from pyrogram.types import Message

from HuTao import app, COMMAND_HANDLER

#----------------TOKEN------------------
TOKEN="1737646273:SSTCWK" #GET THIS TOKEN FROM @NovaXApiBot

#------------------FUNC-------------------
@app.on_message(filters.command("aigen", COMMAND_HANDLER))
async def aigen(_, message:Message):
    if len(message.text.split()) < 2:
        return await message.reply("No Prompt Given To Generate")
    
    prompt = message.text.split(maxsplit=1)[1]

    msg = await message.reply("Wait For Few Mins.. Generating Your Image...")

    loop = asyncio.get_running_loop()
    output = await loop.run_in_executor(None, apiimg, prompt)

    try:
        a = output['image_url']
        await message.reply_photo(a, caption="GENERATED BY [NovaAPI](https://t.me/NovaXMod)")
        await msg.delete()
    except Exception as e:
        await msg.edit(e)

#----------------EVENT LOOP-----------------

def apiimg(prompt):
    output = rr.post("https://nova-api-kp0j.onrender.com/ai", json={'type':'aai', 'prompt':f"{prompt}", 'auth_key':f"{TOKEN}"}).json()
    return output
